version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: sampledb

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./db/queries.sql:/docker-entrypoint-initdb.d/queries.sql
  server:
    build: .
    depends_on:
      - mysql
    expose:
      - 3000
    environment:
      <<: *common-variables
      MYSQL_HOST: mysql
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - .:/usr/src/app
    links:
      - mysql
