version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: fib_d1
  MYSQL_PASSWORD: just_another_password
  MYSQL_DATABASE: fib_d1

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    expose:
      - 3306
    volumes:
      - ./db/queries.sql:/docker-entrypoint-initdb.d/queries.sql
  server:
    build: .
    depends_on:
      - mysql
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
      MYSQL_HOST: mysql
    links:
      - mysql
